name: Deploy Project
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Install dependencies
              run: npm ci

            - name: Lint Codebase
              run: |
                  echo "Linting the codebase..."
                  npm run lint
            - name: Test Codebase
              run: |
                  echo "Running tests..."
                  npm run test
            - name: Build Project
              run: |
                  echo "Building the project..."
                  npm run build
            
            - name: Deploy Project
              run: echo "Deploying the project..."
